# Generated by Django 3.1.7 on 2021-03-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=255, null=True)),
                ('task_completed', models.BooleanField(default=False)),
                ('task_date', models.DateTimeField(verbose_name='Date published')),
            ],
        ),
    ]
